version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-compose
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nbcam
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

  spring:
    build: .
    container_name: spring-compose
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nbcam
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - spring-net

volumes:
  mysql_data:

networks:
  spring-net:
